-- MySQL Script generated by MySQL Workbench
-- 09/24/21 19:59:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema amxqacdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amxqacdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amxqacdd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `amxqacdd` ;

-- -----------------------------------------------------
-- Table `amxqacdd`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`marcas` (
  `mar_codigo` INT NOT NULL COMMENT '',
  `mar_nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`mar_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`veiculos` (
  `vei_codigo` INT NOT NULL COMMENT '',
  `vei_cd_marca` INT NOT NULL COMMENT '',
  `vei_placa` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`vei_codigo`, `vei_cd_marca`)  COMMENT '',
  INDEX `fk_veiculos_marcas1_idx` (`vei_cd_marca` ASC)  COMMENT '',
  CONSTRAINT `fk_veiculos_marcas1`
    FOREIGN KEY (`vei_cd_marca`)
    REFERENCES `amxqacdd`.`marcas` (`mar_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`cidades` (
  `cid_codigo` INT NOT NULL COMMENT '',
  `cid_nome` VARCHAR(45) NULL COMMENT '',
  `cid_uf` VARCHAR(2) NULL COMMENT '',
  PRIMARY KEY (`cid_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`clientes` (
  `cli_codigo` INT NOT NULL COMMENT '',
  `cli_nome` VARCHAR(100) NULL COMMENT '',
  `cli_cd_cidade` INT NOT NULL COMMENT '',
  `Cli_endereco` VARCHAR(100) NULL COMMENT '',
  `Cli_numero` VARCHAR(45) NULL COMMENT '',
  `Cli_complemento` VARCHAR(45) NULL COMMENT '',
  `Cli_bairro` VARCHAR(45) NULL COMMENT '',
  `Cli_cep` VARCHAR(15) NULL COMMENT '',
  `Cli_cnpj_cpf` VARCHAR(20) NULL COMMENT '',
  `Cli_telefone` VARCHAR(20) NULL COMMENT '',
  `Cli_email` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`cli_codigo`)  COMMENT '',
  INDEX `fk_clientes_cidades1_idx` (`cli_cd_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_clientes_cidades1`
    FOREIGN KEY (`cli_cd_cidade`)
    REFERENCES `amxqacdd`.`cidades` (`cid_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`funcionarios` (
  `fun_codigo` INT NOT NULL COMMENT '',
  `fun_nome` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`fun_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`tipo_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`tipo_servico` (
  `tip_codigo` INT NOT NULL COMMENT '',
  `tip_nome` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tip_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`setor` (
  `set_codigo` INT NOT NULL COMMENT '',
  `set_nome` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`set_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`controle_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`controle_veiculos` (
  `con_cd_veiculo` INT NOT NULL COMMENT '',
  `con_cd_cliente` INT NOT NULL COMMENT '',
  INDEX `fk_veiculos_has_clientes_clientes1_idx` (`con_cd_cliente` ASC)  COMMENT '',
  INDEX `fk_veiculos_has_clientes_veiculos_idx` (`con_cd_veiculo` ASC)  COMMENT '',
  PRIMARY KEY (`con_cd_veiculo`, `con_cd_cliente`)  COMMENT '',
  CONSTRAINT `fk_veiculos_has_clientes_veiculos`
    FOREIGN KEY (`con_cd_veiculo`)
    REFERENCES `amxqacdd`.`veiculos` (`vei_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculos_has_clientes_clientes1`
    FOREIGN KEY (`con_cd_cliente`)
    REFERENCES `amxqacdd`.`clientes` (`cli_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`agenda` (
  `age_codigo` INT NOT NULL COMMENT '',
  `age_cd_funcionario` INT NOT NULL COMMENT '',
  `age_cd_tipo` INT NOT NULL COMMENT '',
  `age_cd_setor` INT NOT NULL COMMENT '',
  `age_cd_veiculo` INT NOT NULL COMMENT '',
  `age_cd_cliente` INT NOT NULL COMMENT '',
  `age_status` INT NOT NULL COMMENT '',
  `age_inicial` DATETIME NULL COMMENT '',
  `age_final` DATETIME NULL COMMENT '',
  PRIMARY KEY (`age_codigo`)  COMMENT '',
  INDEX `fk_agenda_funcionarios1_idx` (`age_cd_funcionario` ASC)  COMMENT '',
  INDEX `fk_agenda_setor1_idx` (`age_cd_tipo` ASC)  COMMENT '',
  INDEX `fk_agenda_setor2_idx` (`age_cd_setor` ASC)  COMMENT '',
  INDEX `fk_agenda_controle_veiculos1_idx` (`age_cd_veiculo` ASC, `age_cd_cliente` ASC)  COMMENT '',
  CONSTRAINT `fk_agenda_funcionarios1`
    FOREIGN KEY (`age_cd_funcionario`)
    REFERENCES `amxqacdd`.`funcionarios` (`fun_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_setor1`
    FOREIGN KEY (`age_cd_tipo`)
    REFERENCES `amxqacdd`.`tipo_servico` (`tip_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_setor2`
    FOREIGN KEY (`age_cd_setor`)
    REFERENCES `amxqacdd`.`setor` (`set_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_controle_veiculos1`
    FOREIGN KEY (`age_cd_veiculo` , `age_cd_cliente`)
    REFERENCES `amxqacdd`.`controle_veiculos` (`con_cd_veiculo` , `con_cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`tipo_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`tipo_pagamento` (
  `tip_codigo` INT NOT NULL COMMENT '',
  `tip_nome` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`tip_codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`pagamentos` (
  `pag_codigo` INT NOT NULL COMMENT '',
  `pag_cd_tipo` INT NOT NULL COMMENT '',
  `pag_data` DATE NULL COMMENT '',
  `pag_valor` FLOAT NULL COMMENT '',
  PRIMARY KEY (`pag_codigo`)  COMMENT '',
  INDEX `fk_pagamentos_tipo_pagamento1_idx` (`pag_cd_tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_pagamentos_tipo_pagamento1`
    FOREIGN KEY (`pag_cd_tipo`)
    REFERENCES `amxqacdd`.`tipo_pagamento` (`tip_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amxqacdd`.`movimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amxqacdd`.`movimentos` (
  `mov_codigo` INT NOT NULL COMMENT '',
  `mov_cd_pagamento` INT NOT NULL COMMENT '',
  `mov_cd_agenda` INT NOT NULL COMMENT '',
  `mov_valor` FLOAT NULL COMMENT '',
  `mov_obs` TEXT NULL COMMENT '',
  PRIMARY KEY (`mov_codigo`)  COMMENT '',
  INDEX `fk_movimentos_pagamentos1_idx` (`mov_cd_pagamento` ASC)  COMMENT '',
  INDEX `fk_movimentos_agenda1_idx` (`mov_cd_agenda` ASC)  COMMENT '',
  CONSTRAINT `fk_movimentos_pagamentos1`
    FOREIGN KEY (`mov_cd_pagamento`)
    REFERENCES `amxqacdd`.`pagamentos` (`pag_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentos_agenda1`
    FOREIGN KEY (`mov_cd_agenda`)
    REFERENCES `amxqacdd`.`agenda` (`age_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
