/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.l2g.views;

import br.com.l2g.model.Usuario;
import br.com.l2g.util.Environment;
import br.com.l2g.util.Util;
import br.com.l2g.views.pagamento.ListagemMeioDePagamento;
import br.com.l2g.views.Movimento.ListageMovimento;
import br.com.l2g.views.Sobre.Sobre;
import br.com.l2g.views.agendamento.ListagemAgendamento;
import br.com.l2g.views.cidade.ListagemCidade;
import br.com.l2g.views.cliente.ListagemCliente;
import br.com.l2g.views.veiculo.ListagemVeiculos;
import br.com.l2g.views.funcionario.ListagemFuncionario;
import br.com.l2g.views.servicos.ListagemServico;
import br.com.l2g.views.permissao.ListagemPermissao;
import br.com.l2g.views.usuario.ListagemUsuario;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import org.apache.http.HttpException;
import org.apache.http.client.methods.HttpGet;

/**
 *
 * @author Gustavo Steinhoefel
 */
public class Principal extends javax.swing.JFrame {

    private static final String URL_BASE = Environment.DEV.url();
    private static final String URL_USUARIO = URL_BASE + "usuario/login/";
    private Usuario usuarioTelaPrincipal;

    /**
     * Creates new form Principal
     *
     * @param user
     */
    public Principal(Usuario user) {

        initComponents();
        listarPermissaoUsuario(user);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnCliente1 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnCliente2 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnCliente3 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Wash - Versão 1.00.00");
        setExtendedState(MAXIMIZED_BOTH);

        jToolBar1.setRollover(true);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1476217626_kuser.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.setFocusable(false);
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setMaximumSize(new java.awt.Dimension(87, 57));
        btnCliente.setMinimumSize(new java.awt.Dimension(87, 57));
        btnCliente.setPreferredSize(new java.awt.Dimension(57, 57));
        btnCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCliente);
        jToolBar1.add(jSeparator1);

        btnCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/front_car_vehicle_transport_icon_123462(1).png"))); // NOI18N
        btnCliente1.setText("Veículos");
        btnCliente1.setFocusable(false);
        btnCliente1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente1.setMaximumSize(new java.awt.Dimension(87, 57));
        btnCliente1.setMinimumSize(new java.awt.Dimension(87, 57));
        btnCliente1.setPreferredSize(new java.awt.Dimension(57, 57));
        btnCliente1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCliente1);
        jToolBar1.add(jSeparator8);

        btnCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Driver-License_Male-32.png"))); // NOI18N
        btnCliente2.setText("Agendamento");
        btnCliente2.setFocusable(false);
        btnCliente2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente2.setMaximumSize(new java.awt.Dimension(87, 57));
        btnCliente2.setMinimumSize(new java.awt.Dimension(87, 57));
        btnCliente2.setPreferredSize(new java.awt.Dimension(57, 57));
        btnCliente2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCliente2);
        jToolBar1.add(jSeparator9);

        btnCliente3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1485374000_Mastercard.png"))); // NOI18N
        btnCliente3.setText("Caixa");
        btnCliente3.setFocusable(false);
        btnCliente3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente3.setMaximumSize(new java.awt.Dimension(87, 57));
        btnCliente3.setMinimumSize(new java.awt.Dimension(87, 57));
        btnCliente3.setPreferredSize(new java.awt.Dimension(57, 57));
        btnCliente3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente3ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCliente3);
        jToolBar1.add(jSeparator10);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem título.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu1.setText("Cadastro");

        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator4);

        jMenuItem4.setText("Funcionarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem11.setText("Cidades");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);
        jMenu1.add(jSeparator7);

        jMenuItem2.setText("Veiculos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Serviços");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator3);

        jMenuItem5.setText("Meios de Pagamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Movimento");

        jMenuItem6.setText("Agendamentos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);
        jMenu5.add(jSeparator5);

        jMenuItem12.setText("Caixa");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Configurações");
        jMenu2.add(jSeparator6);

        jMenuItem9.setText("Usuarios");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem7.setText("Permissões");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Relatórios");
        jMenuBar1.add(jMenu4);

        jMenu3.setText("Ajuda");

        jMenuItem10.setText("Sobre");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        listarCliente();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        listarCidade();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        listarCliente();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        listarVeiculos();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        listarFuncionario();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        listarServico();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        listarSobre();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        listarMeioPagamento();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        listarAgendamento();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        listarMovimento();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void btnCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente1ActionPerformed
        listarVeiculos();
    }//GEN-LAST:event_btnCliente1ActionPerformed

    private void btnCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente2ActionPerformed
        listarAgendamento();
    }//GEN-LAST:event_btnCliente2ActionPerformed

    private void btnCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente3ActionPerformed
        listarMovimento();
    }//GEN-LAST:event_btnCliente3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        listarUsuario();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        listarPermissao();
    }//GEN-LAST:event_jMenuItem7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnCliente1;
    private javax.swing.JButton btnCliente2;
    private javax.swing.JButton btnCliente3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void listarPermissaoUsuario(Usuario user) {
        try {

            HttpGet get = new HttpGet(URL_USUARIO + user.getLogin());
            String resposta = Util.enviaRequest(get);
            usuarioTelaPrincipal = Util.jsonToObject(resposta, Usuario.class);

            System.out.println(usuarioTelaPrincipal.toString());

        } catch (IOException | InvalidKeyException | NoSuchAlgorithmException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException | HttpException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void listarCliente() {
        ListagemCliente view = new ListagemCliente(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarCidade() {
        ListagemCidade view = new ListagemCidade(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarVeiculos() {
        ListagemVeiculos view = new ListagemVeiculos(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarFuncionario() {
        ListagemFuncionario view = new ListagemFuncionario(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarServico() {
        ListagemServico view = new ListagemServico(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarSobre() {
        Sobre view = new Sobre();
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarMeioPagamento() {
        ListagemMeioDePagamento view = new ListagemMeioDePagamento(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarAgendamento() {
        ListagemAgendamento view = new ListagemAgendamento(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarMovimento() {
        ListageMovimento view = new ListageMovimento(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }

    private void listarUsuario() {
        ListagemUsuario view = new ListagemUsuario(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setPosicao();
    }

    private void listarPermissao() {
        ListagemPermissao view = new ListagemPermissao(usuarioTelaPrincipal);
        jDesktopPane1.add(view);
        view.setVisible(true);
        view.setPosicao();
    }
}
